name: home
timestamp: 1754668425
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1614615579
positions: {  }
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-3736: 'Logo / Image'
  menu:
    menu-9797: Menu
  sample:
    sample-1892: Showcase
  custom:
    custom-7134: 'Custom HTML'
    custom-9538: 'Custom HTML'
    custom-1277: 'Custom HTML'
    custom-8369: 'Custom HTML'
    custom-9119: 'Custom HTML'
  contentarray:
    contentarray-8583: 'WordPress Posts'
    contentarray-4650: 'WordPress Posts'
  mobile-menu:
    mobile-menu-2793: 'Mobile Menu'
  copyright:
    copyright-7119: Copyright
  widget:
    position-widget-4860: Widget
  social:
    social-7654: Social
  branding:
    branding-8448: Branding
inherit:
  default:
    footer: footer
    copyright-7119: copyright-6945
    position-widget-4860: position-widget-6073
    social-7654: social-4472
    branding-8448: branding-5969
    custom-9119: custom-1246
