name: _offline
timestamp: 1778607028
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1614615579
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-1365: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-9929: Menu
  messages:
    system-messages-3277: 'System Messages'
  content:
    system-content-9704: 'Page Content'
  copyright:
    copyright-6404: Copyright
  spacer:
    spacer-5907: Spacer
  branding:
    branding-8631: Branding
  mobile-menu:
    mobile-menu-1188: Mobile-menu
inherit: {  }
