context:
  -
    is_404: true
    is_attachment: true
    is_author: true
    is_category: true
    is_comments_popup: true
    is_date: true
    is_page: true
    is_preview: true
menu:
  fr:
    1471: true
    1474: true
    1475: true
    1476: true
language:
  -
    fr_FR: true
post:
  post:
    759: true
    740: true
    763: true
    765: true
    749: true
    1053: true
    756: true
    762: true
    766: true
    733: true
    735: true
    750: true
    744: true
    731: true
    746: true
    757: true
    755: true
  post-terms:
    category: true
    category-39: true
    category-22: true
    category-41: true
    language: true
    language-20: true
    post_translations: true
    post_translations-36: true
  page-terms:
    language-20: true
  wp_block-terms:
    language-20: true
taxonomy:
  category:
    0: true
    is_archive: true
    39: true
    22: true
    41: true
  post_tag:
    0: true
    is_archive: true
  link_category:
    0: true
    is_archive: true
archive:
  category:
    0: true
    is_archive: true
    39: true
    22: true
    41: true
  post_tag:
    0: true
    is_archive: true
  link_category:
    0: true
    is_archive: true
