name: fr_base
timestamp: 1760026244
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1614615579
positions:
  breadcrumbs: Breadcrumbs
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-1617: Logo
  menu:
    menu-9797: Menu
  position:
    position-position-3438: Breadcrumbs
  messages:
    system-messages-6143: 'System Messages'
  spacer:
    spacer-2884: Spacer
    spacer-5728: Spacer
  content:
    system-content-3702: 'Page Content'
  mobile-menu:
    mobile-menu-8900: Mobile-menu
  copyright:
    copyright-2122: Copyright
  widget:
    position-widget-6985: Widget
  social:
    social-4771: Social
  branding:
    branding-3099: Branding
  custom:
    custom-6655: 'Custom HTML'
inherit:
  fr:
    footer: footer
    copyright-2122: copyright-2888
    position-widget-6985: position-widget-8367
    social-4771: social-4008
    branding-3099: branding-1550
    custom-6655: custom-8092
