ordering:
  home: ''
  about-us:
    who-we-are: ''
    how-we-started: ''
    challenges: ''
    approach: ''
    our-focus: ''
    'Why-youth-matters?': ''
    governance: ''
  initiatives:
    integrity-building-and-corruption-prevention: ''
    anti-corruption-and-integrity-in-education-system: ''
    studies-and-research-on-corruption: ''
    corruption-reporting-project: ''
    vaccine-education-and-equity-project: ''
    gender-equality-and-social-inclusion: ''
    municipal-transparency-index: ''
  resources:
    radio-show: ''
    publications: ''
    annual-reports-and-financial-statements: ''
  take-action:
    become-a-supporter: ''
    donate-now: ''
    projects-that-need-funding: ''
    volunteering-opportunities: ''
  contact-us: ''
items:
  home:
    object_id: 27
  about-us:
    object_id: 26
  about-us/who-we-are:
    object_id: 26
  about-us/how-we-started:
    object_id: 502
  about-us/challenges:
    object_id: 688
  about-us/approach:
    object_id: 175
  about-us/our-focus:
    object_id: 28
  'about-us/Why-youth-matters?':
    object_id: 499
  about-us/governance:
    object_id: 425
  initiatives:
    attributes: {  }
    link_attributes: {  }
    dropdown: standard
    dropdown_dir: right
    dropdown_hide: '0'
    width: 17rem
  initiatives/integrity-building-and-corruption-prevention:
    object_id: 362
  initiatives/anti-corruption-and-integrity-in-education-system:
    object_id: 639
  initiatives/studies-and-research-on-corruption:
    object_id: 2
  initiatives/corruption-reporting-project:
    object_id: 178
  initiatives/vaccine-education-and-equity-project:
    object_id: 181
  initiatives/gender-equality-and-social-inclusion:
    object_id: 197
  initiatives/municipal-transparency-index:
    object_id: 697
  resources:
    object_id: 30
  resources/radio-show:
    object_id: 496
  resources/publications:
    object_id: 30
  resources/annual-reports-and-financial-statements:
    object_id: 714
  take-action:
    object_id: 252
  take-action/become-a-supporter:
    object_id: 271
  take-action/donate-now:
    object_id: 287
  take-action/projects-that-need-funding:
    object_id: 273
  take-action/volunteering-opportunities:
    object_id: 277
  contact-us:
    object_id: 29
